<?php

/**
 * Implementation of hook_perm()
 */
function pdf_slideshow_perm() {
	return array('administer pdf slideshow');
}

/**
 * Implementation of hook_menu()
 */
function pdf_slideshow_menu($may_cache) {
	$items = array();
	if ($may_cache) {
		$items[] = array(
	      'path' => 'admin/settings/pdfslideshow',
	      'title' => t('PDF Slideshow'),
	      'description' => t('Configure PDF Slideshow settings.'),
	      'callback' => 'drupal_get_form',
	      'callback arguments' => array('pdf_slideshow_admin_settings'),
	      'access' => user_access('administer pdf slideshow'),
	      'type' => MENU_NORMAL_ITEM,
	    );
	}
	else {
		$nid = arg(1);
		$fid = arg(3);
		if (is_numeric($nid) && is_numeric($fid) && $node = node_load($nid)) {
			if ($file = $node->files[$fid]) {
				$items[] = array(
				  'path' => 'node/'. $node->nid.'/file/'.$fid.'/show', 
				  'title' => t('View'),
		          'callback' => 'node_pdf_slideshow',
		          'callback arguments' => array(arg(1), arg(3)),
		          'access' => node_access('view', $node),
		          'type' => MENU_CALLBACK
				);
			}
		} 
			
	}
	return $items;
}

function _pdf_slideshow_get_path ($file, $nid) {
	$dest_path = file_create_path(file_directory_path());
	$dest = realpath($dest_path);
	//var_dump("$dest_path $dest");
	$dest .= '/slideshow/'.$nid.'/'.$file->fid;
	
	return $dest;
}

function _pdf_slideshow_get_rel_path ($file, $nid) {
	$dest_path = file_create_path(file_directory_path());
	//$dest = realpath($dest_path);
	//var_dump("$dest_path $dest");
	$dest = $dest_path . '/slideshow/'.$nid.'/'.$file->fid;

	return $dest;
}


function _pdf_slideshow_get_file_list ($dir) {
	$files = scandir($dir);
	// remove . and ..
	array_shift($files);
	array_shift($files);
	
	return $files;
}

function _pdf_slideshow_normalize_filenames ($dir, $file) {
	$filename = substr($file->filename, 0 , -4);
	for($i = 0; $i < 10; $i++) {
		if (is_file($dir .'/'. $filename . '-' . $i . '.jpg')) {
			rename($dir .'/'. $filename . '-' . $i . '.jpg', $dir .'/'. $filename . '-0' . $i . '.jpg');
		}
	}

}

function _convert_pdf_to_images($file, $nid) {
	/*
	$dest_path = file_create_path(file_directory_path());
	$dest = realpath($dest_path);
	//var_dump("$dest_path $dest");
	$dest .= '/slideshow/'.$nid.'/'.$file->fid;
	*/

	// get destination directory path
	$dest = _pdf_slideshow_get_path($file, $nid);

	if (is_dir($dest)) return true;

	//var_dump("$dest");
	//mkdir($dest, 0777, true);
	//mkdir($dest, 0700, true);
	//if (file_check_directory($dest, FILE_CREATE_DIRECTORY)) {
	if (mkdir($dest, 0777, true)) {
		$source = realpath($file->filepath);
		$target = $dest.'/'. str_replace('.pdf', '.jpg', $file->filename);
		//var_dump($target);
		$convert = variable_get('imagemagick_path', '/usr/bin/convert');
		var_dump("$convert $source $target");
		if (!shell_exec("$convert $source $target")) {
			// normalize filenames
			_pdf_slideshow_normalize_filenames($dest, $file);
			return true;
		}
		//die;
	}
	rmdir($dest);
	return false;

}

function node_pdf_slideshow($nid, $fid) {
	if (is_numeric($nid) && $node = node_load($nid)) {
		if ($file = $node->files[$fid]) {
			if ($file->filemime == 'application/pdf') {
				if (_convert_pdf_to_images($file, $nid)){
					drupal_set_message(t('Preview generated, click on page numbers'));
				}
				else {
					drupal_set_message(t('Error converting files'));
				}
				drupal_goto('node/' . $node->nid);
			}
		}
	} 
}

function pdf_slideshow_admin_settings() {
	$form['general'] = array(
	    '#type' => 'fieldset',
	    '#title' => t('General settings'),
	    '#collapsible' => TRUE,
	    '#collapsed' => FALSE,
	  );
	$form['general']['imagemagick_path'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Imagemagick path'),
	    '#size' => 50,
	    '#default_value' => variable_get('imagemagick_path', exec('/usr/bin/which convert')),
	    '#description' => t('Path to imagemagick.'),
	  );
	return system_settings_form($form);
}

function phptemplate_upload_attachments($files) {
  $node = node_load(arg(1));
  $header = array(t('Attachment'), t('Size'), t('Preview'));
  $rows = array();

  $thickbox_enabled = module_exists('thickbox');
  
  foreach ($files as $file) {
    $file = (object)$file;
    if ($file->list && !$file->remove) {
	  //var_dump($file);
      // Generate valid URL for both existing attachments and preview of new attachments (these have 'upload' in fid)
      $href = file_create_url((strpos($file->fid, 'upload') === FALSE ? $file->filepath : file_create_filename($file->filename, file_create_path())));
      $text = $file->description ? $file->description : $file->filename;

	  $target_dir = _pdf_slideshow_get_path($file, $node->nid);
	  //var_dump($target_dir);
	  if (is_dir($target_dir)) {
			$target_rel_dir = _pdf_slideshow_get_rel_path($file, $node->nid);
			$target_images  = _pdf_slideshow_get_file_list($target_dir);

			//_pdf_slideshow_normalize_filenames($target_dir, $file);
			//var_dump($target_images);
			//var_dump($target_rel_dir);
			$preview_link='';
			if ($thickbox_enabled ) {
				$page = 1;
				foreach ($target_images as $target_image) {
					$preview_link .= '<a href="'. check_url(file_create_url($target_rel_dir . '/' . $target_image)) .'" title="'. $file->filename .'" class="thickbox" rel="file_'.$file->fid . '">'.$page.'</a> ';
					$page++;
				}
			}
		}
	  else {
			$preview_link = l(t('Generate preview'), 'node/'.$node->nid.'/file/'.$file->fid.'/show');
	  }

	  $rows[] = array(
		  l($text, $href),
		  format_size($file->filesize),
		  $preview_link,
	  );
    }
  }
  if (count($rows)) {
    return theme('table', $header, $rows, array('id' => 'attachments'));
  }
}


?>
